project_id = "lgueucxznbqgvhpjzurf"

[functions.sync-ovens]
verify_jwt = false

[functions.init-configurator-data]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.generate-oven-space]
verify_jwt = false

[functions.generate-image-stability]
verify_jwt = false

[functions.generate-image-openai]
verify_jwt = false

[functions.generate-oven-render]
verify_jwt = false

[functions.send-consultation-email]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.import-lead-from-erp]
verify_jwt = false

[functions.sync-to-erp]
verify_jwt = false

[functions.get-session-updates]
verify_jwt = false

[functions.request-new-link]
verify_jwt = false

[functions.send-configurator-link]
verify_jwt = false

[functions.generate-conversion-message]
verify_jwt = false

[functions.generate-blog-article]
verify_jwt = false

[functions.generate-blog-cover]
verify_jwt = false

[functions.translate-blog-article]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.render-blog-post]
verify_jwt = false

[functions.fix-blog-links]
verify_jwt = false

[functions.create-proforma-payment]
verify_jwt = false

[functions.verify-proforma-payment]
verify_jwt = false

[functions.oven-finder-recommend]
verify_jwt = false