project_id = "lgueucxznbqgvhpjzurf"

[functions.sync-ovens]
verify_jwt = false

[functions.init-configurator-data]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.generate-oven-space]
verify_jwt = false

[functions.generate-image-stability]
verify_jwt = false

[functions.generate-image-openai]
verify_jwt = false

[functions.generate-oven-render]
verify_jwt = false

[functions.send-consultation-email]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.request-new-link]
verify_jwt = false